### ISSUE TITLE
No se deben probar detalles de implementación

### ISSUE THREAD

**Issue by evolentini** [jmorellid/Testing#2]
Las pruebas no deberían cambiar si cambia la implementación. Estas pruebas dependen de la implementación de la lista

https://github.com/jmorellid/Testing/blob/d7480ce17b3093185e2add6aecfe058491f8f86e/test/test_lista.py#L45-L61

**Comment by jmorellid** [comment]
Implementado el método __call__ para que la prueba sea independiente de la implementación
